chebureque_admin_panel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resource_list.urls')),
]

resource_list/urls.py
from django.urls import path
from .views import *

app_name = 'resource_list'

urlpatterns = [
    path('', main, name='main_page'),

]

resource_list/models.py
from django.db import models

# Create your models here.
class ResourceModel(models.Model):
    name = models.CharField(max_length = 200)
    url = models.CharField(max_length = 200)
    description = models.TextField(blank=True, null=True)

resource_list/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *


def main(request):
    resources = ResourceModel.objects.all()
    return render(request, 'resource_list/start_page.html', {'resources': resources})


# Create your views here.

resource_list/templates/resource_list/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=10">
    <title>Chebureque</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'resource_list/styles.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
</head>
<body>
    <div>
        <header class="header">
            <p><a href="{% url 'resource_list:main_page' %}">Chebureque Resorce List</a></p>
        </header>
        <div>
            <main class="content">
                {% block content %}
                <p>Hello, Stranger!</p>
                {% endblock %}
            </main>
        </div>

        <footer class="footer">
            <p><a href="{% url 'resource_list:main_page' %}">Chebureque Resorce List</a></p>
        </footer>
    </div>  
</body>
</html>

resource_list/templates/resource_list/start_page.html
{% extends "resource_list/base.html" %}

{% block content %}
    {% for resource in resources %}
    <div>
        <p><a href="{{ resource.url }}">{{ resource.name }}</a></p>
        <p>{{ resource.description }}</p>
    </div>
    {% endfor %}
{% endblock content %}